#' @title Add lines to a plot
#' @description This function is used to add lines to a plot. If only two variables (\code{x} and \code{y1}) are provided, this function collapses to \code{\link[graphics]{lines}}. However, if a third variable is provided (\code{y2}), the line can be coloured by the values of that variable. This can aid inferences regarding associations between two variables and a third variable (or indeed, help emphasise relationships between a response and a single explanatory variable with colour). In this case, the function works by defining a sequence of 'pretty' values across the range of \code{y2} using \code{\link[plot.pretty]{pretty_axis}}. This range of values can become the labels of a colour bar legend in \code{\link[plot.pretty]{add_colour_bar}}. Within this sequence of values, the function defines \code{n} regularly spaced values and, using a user-specified function, a colour is defined for each of these values. The line is plotted by matching each value of \code{y2} with the closest value in this sequence. The larger \code{n}, the smoother the colour scheme (at some computational cost). The approach ensures links between the line drawn and the colour legend added, ensuring both are always 'pretty' (see also \code{\link[plot.pretty]{add_colour_bar}}).
#'
#' @param x A numeric input of x values representing the x coordinates of the line to be plotted.
#' @param y1 A numeric input of y values representing the y coordinates of the lines to be plotted.
#' @param y2 (optional) A numeric input of values which will be used to colour the lines plotted.
#' @param dat (optional) A dataframe with columns 'x', 'y1' and (optionally) 'y2' can be provided instead of \code{x}, \code{y1} and \code{y2}.
#' @param pretty_axis_args A list of arguments passed to \code{\link[plot.pretty]{pretty_axis}}. This is used to define a sequence of pretty values, between the limits of which \code{n} colours are drawn. Modifying \code{pretty_axis_args} predominantly affects the colour bar legend that is added to plots (see Examples in \code{\link[plot.pretty]{add_colour_bar}}).
#' @param n (optional) The number of bins in \code{y2} for which a colour is assigned. Larger numbers produce smoother colour schemes but these can be slower to run.
#' @param f (optional) A function used to define the colours that are used to colour the line according to \code{y2}.
#' @param output A numeric input specifying the output format: \code{1}, list; \code{2}, plot; \code{3}, plot and list (see Value).
#' @param ... Additional arguments passed to \code{\link[graphics]{lines}}, if only \code{x} and \code{y1} are provided, or \code{\link[graphics]{arrows}} if \code{y2} is also provided.
#'
#' @returns A line and/or a list. The list contains two elements. (1) \code{data_legend} is a dataframe with two columns: 'x', a sequence of n values across limits (either defined by the user or automatically by \code{\link[plot.pretty]{pretty_axis}}) values; and 'col', referring to corresponding colours. This can be passed to \code{\link[plot.pretty]{add_colour_bar}} to plot a legend. (2) \code{axis_legend} is a list of arguments, generated by \code{\link[plot.pretty]{pretty_axis}} that can be passed to \code{\link[plot.pretty]{add_colour_bar}} to add an axis to the legend.
#'
#' @examples
#'
#' #### Generate some example data
#' x <- 1:1000
#' y1 <- runif(length(x), 0, 100)
#' y2 <- x
#'
#' #### Example (1)
#' plot(x, y1)
#' add_lines(x = x, y1 = y1, y2 = y2, n = 100)
#'
#' @seealso \code{\link[plot.pretty]{pretty_axis}}, \code{\link[plot.pretty]{add_colour_bar}}
#'
#' @author Edward Lavender
#' @export
#'

#########################################
#########################################
#### add_lines()

add_lines <-
  function(x,
           y1,
           y2 = NULL,
           dat = NULL,
           pretty_axis_args = list(pretty = list(n = 5)),
           n = 100,
           f = grDevices::colorRampPalette(c("red", "blue")),
           output = 3,...){

    #### Define dataframe
    if(is.null(dat)){
      dat <- data.frame(x = x, y1 = y1)
      if(!is.null(y2)){
        dat$y2 <- y2
      }
    }

    #### Plot normal line if y2 not specified
    if(is.null(dat$y2)){
      graphics::lines(dat$x, dat$y1,...)

    #### Plot coloured line if y2 specified
    } else{

      #### Method
      # 1) Define pretty legend labels using pretty_axis
      # 2) Define a much more numerous sequence of values along this range at which colours will be defined

      #### Define legend axis ('colour_bar_axis') using pretty_axis based on y2
      dpa <- list(side = 4,
                  x = list(dat$y2),
                  lim = list(),
                  pretty = list(),
                  units = list(),
                  axis = list(pos = 1),
                  axis_ls = NULL,
                  add = FALSE,
                  return_list = TRUE)
      pretty_axis_args <- rlist::list.merge(list(add = FALSE), pretty_axis_args, dpa)
      colour_bar_axis <- do.call("pretty_axis", pretty_axis_args)
      lim <- colour_bar_axis$`4`$lim

      #### Define data to plot a coloured line
      # Define regular sequence along pretty axis at which we'll define colours
      y2_seq <- seq(lim[1], lim[2], length.out = n)
      lcs <- length(y2_seq)
      # Determine the position of each of the values of y2 in y2_seq
      dat$order = findInterval(dat$y2, y2_seq)
      # Define a sequence of colours using the function provided:
      cols <- f(lcs)
      # Associate each observation with a colour:
      dat$row <- 1:nrow(dat)
      dat$col <- cols[dat$order[dat$row]]

      #### Plot a coloured line
      if(output %in% c(2, 3)){
        # Define the start and end coordinates of each arrow segment
        # ... and the associated colour:
        nrw_dat <- nrow(dat)
        x0 <- dat$x[1:(nrw_dat-1)]
        x1 <- dat$x[2:nrw_dat]
        y0 <- dat$y1[1:(nrw_dat-1)]
        y1 <- dat$y1[2:nrw_dat]
        col <- dat$col[1:(nrw_dat-1)]
        # Use arrows() to add the colour lines; this is by far the
        # ... fastest approach.
        # We'll suppress the arrows so they are not visible:
        graphics::arrows(x0, y0, x1, y1, length = 0, angle = 0, col = col,...)
      }

      #### Return a list if requested
      # These can be called by associated functions e.g. colour.bar()
      # ... which plots a legend for the coloured line.
      if(output %in% c(1, 3)){
        # data_line <- dat
        data_legend <- data.frame(x = y2_seq, col = cols)
        data_legend$col <- as.character(data_legend$col)
        axis_legend <- colour_bar_axis
        output <- list(data_legend = data_legend, axis_legend = axis_legend)
        return(output)

      } # close if(output %in% c("plot_and_values", "values_only")){

    } # close else{}

} # close function


#### End of function.
################################################
################################################
